//! # android-cpufeatures-sys
//!
//! Raw bindings to Android NDK's `cpufeatures` library for Rust.
//!
//! [Check-out the library's official docs](https://developer.android.com/ndk/guides/cpu-features.html). It is not duplicated here.
//!
//! Don't miss `android_getCpuIdArm()` and `android_setCpuArm()` - since they are filtered with
//! `#[cfg(target_arch="arm")]`, they don't appear in this generated documentation.  
//! Therefore, it's advisable to take a look at `src/lib.rs`.

// Generated by bindgen, then hand-edited.

#![doc(html_root_url = "https://docs.rs/android-cpufeatures-sys/2.0.0")]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]


use std::os::raw::c_int;

#[link(name = "cpufeatures")]
extern {
    pub fn android_getCpuCount() -> c_int;
    pub fn android_getCpuFamily() -> AndroidCpuFamily;
    pub fn android_getCpuFeatures() -> u64;
    pub fn android_setCpu(cpu_count: c_int, cpu_features: u64) -> c_int;
}
#[link(name = "cpufeatures")]
#[cfg(target_arch="arm")]
extern {
    pub fn android_getCpuIdArm() -> u32;
    pub fn android_setCpuArm(cpu_count: c_int, cpu_features: u64, cpu_id: u32) -> c_int;
}


#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum AndroidCpuFamily {
    ANDROID_CPU_FAMILY_UNKNOWN = 0,
    ANDROID_CPU_FAMILY_ARM = 1,
    ANDROID_CPU_FAMILY_X86 = 2,
    ANDROID_CPU_FAMILY_MIPS = 3,
    ANDROID_CPU_FAMILY_ARM64 = 4,
    ANDROID_CPU_FAMILY_X86_64 = 5,
    ANDROID_CPU_FAMILY_MIPS64 = 6,
    ANDROID_CPU_FAMILY_MAX = 7,
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum ArmFeature {
    ANDROID_CPU_ARM_FEATURE_ARMv7 = 1,
    ANDROID_CPU_ARM_FEATURE_VFPv3 = 2,
    ANDROID_CPU_ARM_FEATURE_NEON = 4,
    ANDROID_CPU_ARM_FEATURE_LDREX_STREX = 8,
    ANDROID_CPU_ARM_FEATURE_VFPv2 = 16,
    ANDROID_CPU_ARM_FEATURE_VFP_D32 = 32,
    ANDROID_CPU_ARM_FEATURE_VFP_FP16 = 64,
    ANDROID_CPU_ARM_FEATURE_VFP_FMA = 128,
    ANDROID_CPU_ARM_FEATURE_NEON_FMA = 256,
    ANDROID_CPU_ARM_FEATURE_IDIV_ARM = 512,
    ANDROID_CPU_ARM_FEATURE_IDIV_THUMB2 = 1024,
    ANDROID_CPU_ARM_FEATURE_iWMMXt = 2048,
    ANDROID_CPU_ARM_FEATURE_AES = 4096,
    ANDROID_CPU_ARM_FEATURE_PMULL = 8192,
    ANDROID_CPU_ARM_FEATURE_SHA1 = 16384,
    ANDROID_CPU_ARM_FEATURE_SHA2 = 32768,
    ANDROID_CPU_ARM_FEATURE_CRC32 = 65536,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Arm64Feature {
    ANDROID_CPU_ARM64_FEATURE_FP = 1,
    ANDROID_CPU_ARM64_FEATURE_ASIMD = 2,
    ANDROID_CPU_ARM64_FEATURE_AES = 4,
    ANDROID_CPU_ARM64_FEATURE_PMULL = 8,
    ANDROID_CPU_ARM64_FEATURE_SHA1 = 16,
    ANDROID_CPU_ARM64_FEATURE_SHA2 = 32,
    ANDROID_CPU_ARM64_FEATURE_CRC32 = 64,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum X86Feature {
    ANDROID_CPU_X86_FEATURE_SSSE3 = 1,
    ANDROID_CPU_X86_FEATURE_POPCNT = 2,
    ANDROID_CPU_X86_FEATURE_MOVBE = 4,
    ANDROID_CPU_X86_FEATURE_SSE4_1 = 8,
    ANDROID_CPU_X86_FEATURE_SSE4_2 = 16,
    ANDROID_CPU_X86_FEATURE_AES_NI = 32,
    ANDROID_CPU_X86_FEATURE_AVX = 64,
    ANDROID_CPU_X86_FEATURE_RDRAND = 128,
    ANDROID_CPU_X86_FEATURE_AVX2 = 256,
    ANDROID_CPU_X86_FEATURE_SHA_NI = 512,
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum MipsFeature {
    ANDROID_CPU_MIPS_FEATURE_R6 = 1,
    ANDROID_CPU_MIPS_FEATURE_MSA = 2,
}
